# Generated by Django 2.2.1 on 2019-05-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20190515_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixtures',
            name='team_name',
        ),
        migrations.AddField(
            model_name='fixtures',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_team2', to='entries.Teams'),
        ),
        migrations.AddField(
            model_name='fixtures',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_team1', to='entries.Teams'),
        ),
        migrations.AddField(
            model_name='fixtures',
            name='key',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
