# Generated by Django 2.2.1 on 2019-05-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20190515_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixtures',
            name='key',
        ),
    ]
