# Generated by Django 2.2.1 on 2019-06-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_entry_data_fixture_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_data',
            name='entry_player1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='player_score_1', to='entries.Players'),
        ),
        migrations.AlterField(
            model_name='entry_data',
            name='entry_player2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='player_score_2', to='entries.Players'),
        ),
        migrations.AlterField(
            model_name='entry_data',
            name='entry_player3',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='player_score_3', to='entries.Players'),
        ),
        migrations.AlterField(
            model_name='entry_data',
            name='entry_player4',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='player_score_4', to='entries.Players'),
        ),
    ]
