# Generated by Django 2.2.1 on 2019-05-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_remove_fixtures_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='game_week',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
