# Generated by Django 2.2.1 on 2019-06-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20190610_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='usr_teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'verbose_name': 'player', 'verbose_name_plural': 'players'},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='user_teamname',
            new_name='user_teams',
        ),
    ]
