# Generated by Django 2.2.1 on 2019-06-11 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_auto_20190611_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixtures',
            options={'verbose_name': 'fixture', 'verbose_name_plural': 'fixtures'},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
        migrations.AddField(
            model_name='usr_teams',
            name='team_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
