# Generated by Django 2.2.1 on 2019-05-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20190523_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='year_in_school',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('TRUE', 'True'), ('FASLE', 'False')], default='TRUE', max_length=2),
        ),
    ]
