# Generated by Django 2.2.1 on 2019-06-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20190611_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_teams',
            new_name='comments',
        ),
    ]
