# Generated by Django 2.2.1 on 2019-06-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20190611_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usr_teams',
            options={'verbose_name': 'user team', 'verbose_name_plural': 'user teams'},
        ),
        migrations.RenameField(
            model_name='configdata',
            old_name='current_gw',
            new_name='gameweek',
        ),
        migrations.RenameField(
            model_name='configdata',
            old_name='current_season',
            new_name='season',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='entry_season',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='fixture_id',
        ),
        migrations.RemoveField(
            model_name='results',
            name='season',
        ),
        migrations.AlterField(
            model_name='entry_data',
            name='entry_gw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Entry_Game_Week', to='entries.configdata'),
        ),
        migrations.AlterField(
            model_name='entry_data',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Entry_Team', to='entries.configdata'),
        ),
        migrations.AlterField(
            model_name='fixtures',
            name='game_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fixture_Game_Week', to='entries.configdata'),
        ),
        migrations.AlterField(
            model_name='question',
            name='game_week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question_Game_Week', to='entries.configdata'),
        ),
        migrations.AlterField(
            model_name='results',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Results_Team', to='entries.configdata'),
        ),
    ]
