# Generated by Django 2.2.1 on 2019-05-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20190523_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='game_week',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
