# Generated by Django 2.2.1 on 2019-05-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_auto_20190523_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('TRUE', 'True'), ('FASLE', 'False')], default='TRUE', max_length=5),
        ),
    ]
