# Generated by Django 2.2.1 on 2019-06-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_auto_20190611_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtures',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
