# Generated by Django 2.2.1 on 2019-05-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_auto_20190523_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('gw1score', models.PositiveIntegerField(default=0)),
                ('gw2score', models.PositiveIntegerField(default=0)),
                ('gw3score', models.PositiveIntegerField(default=0)),
                ('gw4score', models.PositiveIntegerField(default=0)),
                ('gw5score', models.PositiveIntegerField(default=0)),
                ('gw6score', models.PositiveIntegerField(default=0)),
                ('gw7score', models.PositiveIntegerField(default=0)),
                ('gw8score', models.PositiveIntegerField(default=0)),
                ('gw9score', models.PositiveIntegerField(default=0)),
                ('gw10score', models.PositiveIntegerField(default=0)),
                ('gw11score', models.PositiveIntegerField(default=0)),
                ('gw12score', models.PositiveIntegerField(default=0)),
                ('gw13score', models.PositiveIntegerField(default=0)),
                ('gw14score', models.PositiveIntegerField(default=0)),
                ('gw15score', models.PositiveIntegerField(default=0)),
                ('gw16score', models.PositiveIntegerField(default=0)),
                ('gw17score', models.PositiveIntegerField(default=0)),
                ('gw18score', models.PositiveIntegerField(default=0)),
                ('gw19score', models.PositiveIntegerField(default=0)),
                ('gw20score', models.PositiveIntegerField(default=0)),
                ('gw21score', models.PositiveIntegerField(default=0)),
                ('gw22score', models.PositiveIntegerField(default=0)),
                ('gw23score', models.PositiveIntegerField(default=0)),
                ('gw24score', models.PositiveIntegerField(default=0)),
                ('gw25score', models.PositiveIntegerField(default=0)),
                ('gw26score', models.PositiveIntegerField(default=0)),
                ('gw27score', models.PositiveIntegerField(default=0)),
                ('gw29score', models.PositiveIntegerField(default=0)),
                ('gw30score', models.PositiveIntegerField(default=0)),
                ('gw31score', models.PositiveIntegerField(default=0)),
                ('gw32score', models.PositiveIntegerField(default=0)),
                ('gw33score', models.PositiveIntegerField(default=0)),
                ('gw34score', models.PositiveIntegerField(default=0)),
                ('gw35score', models.PositiveIntegerField(default=0)),
                ('gw36score', models.PositiveIntegerField(default=0)),
                ('gw37score', models.PositiveIntegerField(default=0)),
                ('gw38score', models.PositiveIntegerField(default=0)),
                ('gw39score', models.PositiveIntegerField(default=0)),
                ('gw40score', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='players',
            old_name='player_fname',
            new_name='player_name',
        ),
        migrations.RemoveField(
            model_name='players',
            name='player_lname',
        ),
    ]
