# Generated by Django 2.2.1 on 2019-06-11 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0010_auto_20190611_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='configdata',
            name='gw_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configdata',
            name='gw_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configdata',
            name='gw_deadline',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
