# Generated by Django 2.2.1 on 2019-06-11 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_auto_20190611_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configdata',
            options={'verbose_name': 'Game Week Config', 'verbose_name_plural': 'Game Week Config'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('TRUE', 'True'), ('FASLE', 'False')], default='TRUE', max_length=5)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question_Number', to='entries.Question')),
            ],
        ),
    ]
