# Generated by Django 2.2.1 on 2019-05-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0011_auto_20190529_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='configdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_gw', models.PositiveIntegerField(default=0)),
                ('current_season', models.PositiveIntegerField(default=2019)),
            ],
        ),
        migrations.CreateModel(
            name='entry_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_gw', models.PositiveIntegerField(default=0)),
                ('entry_season', models.PositiveIntegerField(default=2019)),
                ('team_id', models.PositiveIntegerField(default=2019)),
                ('score_home_fix1', models.PositiveIntegerField(default=0)),
                ('score_home_fix2', models.PositiveIntegerField(default=0)),
                ('score_home_fix3', models.PositiveIntegerField(default=0)),
                ('score_home_fix4', models.PositiveIntegerField(default=0)),
                ('score_home_fix5', models.PositiveIntegerField(default=0)),
                ('score_home_fix6', models.PositiveIntegerField(default=0)),
                ('score_home_fix7', models.PositiveIntegerField(default=0)),
                ('score_home_fix8', models.PositiveIntegerField(default=0)),
                ('score_home_fix9', models.PositiveIntegerField(default=0)),
                ('score_home_fix10', models.PositiveIntegerField(default=0)),
                ('score_away_fix1', models.PositiveIntegerField(default=0)),
                ('score_away_fix2', models.PositiveIntegerField(default=0)),
                ('score_away_fix3', models.PositiveIntegerField(default=0)),
                ('score_away_fix4', models.PositiveIntegerField(default=0)),
                ('score_away_fix5', models.PositiveIntegerField(default=0)),
                ('score_away_fix6', models.PositiveIntegerField(default=0)),
                ('score_away_fix7', models.PositiveIntegerField(default=0)),
                ('score_away_fix8', models.PositiveIntegerField(default=0)),
                ('score_away_fix9', models.PositiveIntegerField(default=0)),
                ('score_away_fix10', models.PositiveIntegerField(default=0)),
                ('score_away_fix11', models.PositiveIntegerField(default=0)),
                ('score_tg', models.PositiveIntegerField(default=0)),
                ('entry_q1', models.CharField(max_length=5)),
                ('entry_q2', models.CharField(max_length=5)),
                ('entry_q3', models.CharField(max_length=5)),
                ('entry_q4', models.CharField(max_length=5)),
                ('entry_q5', models.CharField(max_length=5)),
                ('entry_q6', models.CharField(max_length=5)),
                ('entry_q7', models.CharField(max_length=5)),
                ('entry_q8', models.CharField(max_length=5)),
                ('entry_q9', models.CharField(max_length=5)),
                ('entry_q10', models.CharField(max_length=5)),
                ('entry_player1', models.CharField(max_length=20)),
                ('entry_player2', models.CharField(max_length=20)),
                ('entry_player3', models.CharField(max_length=20)),
                ('entry_player4', models.CharField(max_length=20)),
            ],
        ),
    ]
