# Generated by Django 2.2.1 on 2019-06-11 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0012_auto_20190611_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry_data',
            old_name='score_away_fix1',
            new_name='score_away',
        ),
        migrations.RenameField(
            model_name='entry_data',
            old_name='score_away_fix10',
            new_name='score_home',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='entry_player1',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='entry_player2',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='entry_player3',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='entry_player4',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='entry_q1',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='entry_q10',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='entry_q2',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='entry_q3',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='entry_q4',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='entry_q5',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='entry_q6',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='entry_q7',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='entry_q8',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='entry_q9',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_away_fix11',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_away_fix2',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_away_fix3',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_away_fix4',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_away_fix5',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_away_fix6',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_away_fix7',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_away_fix8',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_away_fix9',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_home_fix1',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_home_fix10',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_home_fix2',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_home_fix3',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_home_fix4',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_home_fix5',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_home_fix6',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_home_fix7',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_home_fix8',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_home_fix9',
        ),
        migrations.RemoveField(
            model_name='entry_data',
            name='score_tg',
        ),
        migrations.CreateModel(
            name='Total_Goal_Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_tg', models.PositiveIntegerField(default=0)),
                ('entry_gw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TG_Game_Week', to='entries.configdata')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TG_Team', to='entries.configdata')),
            ],
        ),
        migrations.CreateModel(
            name='entry_scorers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_gw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorers_gw_entry', to='entries.configdata')),
                ('entry_player1', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='player_score_1', to='entries.Players')),
                ('entry_player2', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='player_score_2', to='entries.Players')),
                ('entry_player3', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='player_score_3', to='entries.Players')),
                ('entry_player4', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='player_score_4', to='entries.Players')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorers_team_entry', to='entries.configdata')),
            ],
        ),
        migrations.CreateModel(
            name='entry_q_answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_answer', models.CharField(choices=[('TRUE', 'True'), ('FASLE', 'False')], default='TRUE', max_length=5)),
                ('entry_gw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qanwsers_Game_Week', to='entries.configdata')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qanwsers_question_id', to='entries.Question')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qanwsers_team', to='entries.configdata')),
            ],
        ),
    ]
