# Generated by Django 2.2.1 on 2019-06-11 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0013_auto_20190611_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_data',
            name='fixture_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Entry_Team', to='entries.Fixtures'),
        ),
        migrations.AlterField(
            model_name='entry_data',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Entry_Team', to='entries.usr_teams'),
        ),
        migrations.AlterField(
            model_name='entry_q_answers',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qanwsers_team', to='entries.usr_teams'),
        ),
        migrations.AlterField(
            model_name='entry_scorers',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorers_team_entry', to='entries.usr_teams'),
        ),
        migrations.AlterField(
            model_name='total_goal_entry',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TG_Team', to='entries.usr_teams'),
        ),
    ]
