# Generated by Django 2.2.1 on 2019-07-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0014_auto_20190611_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='teamname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
