# Generated by Django 2.2.1 on 2019-07-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0016_entry_data_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='fix_weekid',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
