# Generated by Django 2.2.1 on 2019-08-03 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0017_fixtures_fix_weekid'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_data_new',
            name='score_tg',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='scorer_player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_scorer', to='entries.Players'),
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='scorer_player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_scorer', to='entries.Players'),
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='scorer_player3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player3_scorer', to='entries.Players'),
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='scorer_player4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player4_scorer', to='entries.Players'),
        ),
    ]
