# Generated by Django 2.2.1 on 2019-08-12 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0018_auto_20190803_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='gw_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_home_fid1', models.PositiveIntegerField(default=0)),
                ('score_away_fid1', models.PositiveIntegerField(default=0)),
                ('score_home_fid2', models.PositiveIntegerField(default=0)),
                ('score_away_fid2', models.PositiveIntegerField(default=0)),
                ('score_home_fid3', models.PositiveIntegerField(default=0)),
                ('score_away_fid3', models.PositiveIntegerField(default=0)),
                ('score_home_fid4', models.PositiveIntegerField(default=0)),
                ('score_away_fid4', models.PositiveIntegerField(default=0)),
                ('score_home_fid5', models.PositiveIntegerField(default=0)),
                ('score_away_fid5', models.PositiveIntegerField(default=0)),
                ('score_home_fid6', models.PositiveIntegerField(default=0)),
                ('score_away_fid6', models.PositiveIntegerField(default=0)),
                ('score_home_fid7', models.PositiveIntegerField(default=0)),
                ('score_away_fid7', models.PositiveIntegerField(default=0)),
                ('score_home_fid8', models.PositiveIntegerField(default=0)),
                ('score_away_fid8', models.PositiveIntegerField(default=0)),
                ('score_home_fid9', models.PositiveIntegerField(default=0)),
                ('score_away_fid9', models.PositiveIntegerField(default=0)),
                ('score_home_fid10', models.PositiveIntegerField(default=0)),
                ('score_away_fid10', models.PositiveIntegerField(default=0)),
                ('score_tg', models.PositiveIntegerField(default=0)),
                ('fixture_id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_f1', to='entries.Fixtures')),
                ('fixture_id10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_f10', to='entries.Fixtures')),
                ('fixture_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_f2', to='entries.Fixtures')),
                ('fixture_id3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_f3', to='entries.Fixtures')),
                ('fixture_id4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_f4', to='entries.Fixtures')),
                ('fixture_id5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_f5', to='entries.Fixtures')),
                ('fixture_id6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_f6', to='entries.Fixtures')),
                ('fixture_id7', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_f7', to='entries.Fixtures')),
                ('fixture_id8', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_f8', to='entries.Fixtures')),
                ('fixture_id9', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_f9', to='entries.Fixtures')),
            ],
        ),
        migrations.DeleteModel(
            name='Results',
        ),
    ]
