# Generated by Django 3.2.7 on 2021-10-05 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0020_gw_results_entry_gw'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_data_new',
            name='scorer_player1_ff',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='scorer_player2_ff',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='scorer_player3_ff',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='scorer_player4_ff',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.CreateModel(
            name='user_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_fix1', models.PositiveIntegerField(default=0)),
                ('points_fix2', models.PositiveIntegerField(default=0)),
                ('points_fix3', models.PositiveIntegerField(default=0)),
                ('points_fix4', models.PositiveIntegerField(default=0)),
                ('points_fix5', models.PositiveIntegerField(default=0)),
                ('points_fix6', models.PositiveIntegerField(default=0)),
                ('points_fix7', models.PositiveIntegerField(default=0)),
                ('points_fix8', models.PositiveIntegerField(default=0)),
                ('points_fix9', models.PositiveIntegerField(default=0)),
                ('points_fix10', models.PositiveIntegerField(default=0)),
                ('results_score', models.PositiveIntegerField(default=0)),
                ('tg_score', models.PositiveIntegerField(default=0)),
                ('entry_gw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr_res_GW', to='entries.configdata')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usr_res_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
