# Generated by Django 3.2.7 on 2021-10-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0021_auto_20211005_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry_data_new',
            name='scorer_player1',
        ),
        migrations.RemoveField(
            model_name='entry_data_new',
            name='scorer_player2',
        ),
        migrations.RemoveField(
            model_name='entry_data_new',
            name='scorer_player3',
        ),
        migrations.RemoveField(
            model_name='entry_data_new',
            name='scorer_player4',
        ),
    ]
