# Generated by Django 3.2.7 on 2021-10-05 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0022_auto_20211005_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_data_new',
            name='question_answer_id1',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='question_id1',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='qid_f1', to='entries.question'),
            preserve_default=False,
        ),
    ]
