# Generated by Django 3.2.7 on 2021-10-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0025_remove_entry_data_new_question_answer_id1'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_data_new',
            name='question_answer_id1',
            field=models.BooleanField(default=0),
        ),
    ]
