# Generated by Django 3.2.7 on 2021-10-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0026_entry_data_new_question_answer_id1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_goal_entry',
            name='score_tg',
            field=models.PositiveIntegerField(choices=[(True, 'True'), (False, 'False')], default=False),
        ),
    ]
