# Generated by Django 3.2.7 on 2021-10-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0027_alter_total_goal_entry_score_tg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_data_new',
            name='question_answer_id1',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=False),
        ),
        migrations.AlterField(
            model_name='total_goal_entry',
            name='score_tg',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
