# Generated by Django 3.2.7 on 2021-10-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0028_auto_20211005_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_data_new',
            name='question_answer_id1',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default=1),
        ),
    ]
