# Generated by Django 3.2.7 on 2021-10-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0029_alter_entry_data_new_question_answer_id1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry_data_new',
            name='question_answer_id1',
            field=models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], default='TRUE', max_length=5),
        ),
    ]
