# Generated by Django 3.2.7 on 2021-10-07 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0030_alter_entry_data_new_question_answer_id1'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_data_new',
            name='question_answer_id2',
            field=models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], default='TRUE', max_length=5),
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='question_id2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qid_f2', to='entries.question'),
            preserve_default=False,
        ),
    ]
