# Generated by Django 3.2.7 on 2021-10-07 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0031_auto_20211007_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry_data_new',
            name='question_answer_id3',
            field=models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], default='TRUE', max_length=5),
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='question_answer_id4',
            field=models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], default='TRUE', max_length=5),
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='question_answer_id5',
            field=models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], default='TRUE', max_length=5),
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='question_answer_id6',
            field=models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], default='TRUE', max_length=5),
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='question_answer_id7',
            field=models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], default='TRUE', max_length=5),
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='question_answer_id8',
            field=models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False')], default='TRUE', max_length=5),
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='question_id3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qid_f3', to='entries.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='question_id4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qid_f4', to='entries.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='question_id5',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qid_f5', to='entries.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='question_id6',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qid_f6', to='entries.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='question_id7',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qid_f7', to='entries.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry_data_new',
            name='question_id8',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='qid_f8', to='entries.question'),
            preserve_default=False,
        ),
    ]
